namespace HospitalAssetTracker.Models
{
    public enum ProcurementType
    {
        Hardware = 1,
        Software = 2,
        Services = 3,
        Consumables = 4,
        Infrastructure = 5,
        Maintenance = 6,
        Training = 7,
        NewEquipment = 8,
        Replacement = 9,
        Equipment = 10,
        Capital = 11,
        Operational = 12,
        Emergency = 13,
        Other = 99
    }

    public enum ProcurementCategory
    {
        Desktop = 1,
        Laptop = 2,
        Server = 3,
        NetworkEquipment = 4,
        Printer = 5,
        Monitor = 6,
        SoftwareLicense = 7,
        OperatingSystem = 8,
        SecuritySoftware = 9,
        ProductivitySoftware = 10,
        MaintenanceContract = 11,
        SupportServices = 12,
        ConsultingServices = 13,
        TrainingServices = 14,
        Cables = 15,
        Accessories = 16,
        Consumables = 17,
        ITEquipment = 18,
        Maintenance = 19, // Added
        Critical = 20,
        High = 21,
        Medium = 22,
        Low = 23,
        Other = 99
    }

    public enum ProcurementStatus
    {
        Draft = 1,
        Pending = 2,
        PendingApproval = 2,
        Approved = 3,
        Rejected = 4,
        InProcurement = 5,
        InProgress = 5,
        OrderPlaced = 6,
        Ordered = 6,
        PartiallyReceived = 7,
        PartiallyDelivered = 7,
        Delivered = 8,
        Received = 9,
        Completed = 10,
        Cancelled = 11
    }

    public enum ProcurementMethod
    {
        DirectPurchase = 1,
        FrameworkAgreement = 2,
        CompetitiveBidding = 3,
        FormalTender = 4,
        EmergencyProcurement = 5
    }

    public enum ProcurementSource
    {
        Manual = 1,
        RequestModule = 2,
        InventoryThreshold = 3,
        AssetLifecycle = 4,
        AutoGenerated = 5
    }

    public enum ProcurementPriority
    {
        Low = 1,
        Medium = 2,
        High = 3,
        Critical = 4 // Added
    }

    public enum ProcurementActivityType
    {
        RequestCreated = 1,
        ApprovalPending = 2,
        Approved = 3,
        Rejected = 4,
        VendorSelection = 5,
        QuoteRequested = 6,
        QuoteReceived = 7,
        OrderPlaced = 8,
        PartiallyReceived = 9,
        Received = 10,
        ShipmentComplete = 11,
        PaymentProcessed = 12,
        ContractSigned = 13,
        ServiceActivated = 14,
        TrainingCompleted = 15,
        Created = 16,
        Updated = 17,
        SubmittedForApproval = 18,
        ProcessingStarted = 19,
        Other = 99
    }

    public enum ProcurementApprovalLevel
    {
        Manager = 1,
        DepartmentHead = 2,
        Executive = 3,
        Finance = 4,
        IT = 5
    }

    public enum ProcurementApprovalStatus
    {
        Pending = 1,
        Approved = 2,
        Rejected = 3,
        Escalated = 4
    }

    public enum ProcurementDocumentType
    {
        Quote = 1,
        PurchaseOrder = 2,
        Invoice = 3,
        DeliveryNote = 4,
        WarrantyDocument = 5,
        Certificate = 6,
        Specification = 7,
        Contract = 8,
        Other = 99
    }

    public enum VendorStatus
    {
        Active = 0,
        Inactive = 1,
        Pending = 2,
        Approved = 3,
        Rejected = 4,
        Suspended = 5,
        Blacklisted = 6
    }
}
